spring:
  application:
    name: Ims-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/ims_db
    username: postgres
    password: Yug123
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: ims_super_secret_key_must_be_32_characters!!
  expiration: 86400000
